language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - DB=postgres://postgres@localhost/test
before_script:
  - psql -c 'create database quantified_self;' -U postgres
