language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - DB=postgres://postgres@localhost/test
before_script:
  - psql -c 'create database test;' -U postgres
  - node ./replay.js -d postgres://postgres@localhost/test
